# Generated by Django 5.1.7 on 2025-03-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_jobpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='date',
            field=models.DateTimeField(auto_now_add=True, max_length=40, unique=True),
        ),
    ]
