# Generated by Django 5.1.7 on 2025-03-25 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_skills_jobpost_skils'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='skils',
            new_name='skills',
        ),
    ]
